apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-dumpdisk
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 300G
---
apiVersion: v1
kind: Pod
metadata:
  name: gcloud
spec:
  containers:
  - image: navikt/gcloud-psql:9
    imagePullPolicy: IfNotPresent
    name: gcloud
    volumeMounts:
    - mountPath: /etc/ssl/ca-bundle.pem
      name: ca-bundle-pem
      readOnly: true
      subPath: ca-bundle.pem
    - mountPath: /data
      name: dumpdisk
    - mountPath: /var/run/secrets/nais.io/migration-user
      name: migration-user
      readOnly: true
  volumes:
  - configMap:
      defaultMode: 420
      name: ca-bundle-pem
    name: ca-bundle-pem
  - persistentVolumeClaim:
      claimName: pvc-dumpdisk
    name: dumpdisk
  - secret:
      defaultMode: 420
      secretName: migration-user
    name: migration-user
