apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: gcloud
spec:
  image: europe-north1-docker.pkg.dev/nais-io/nais/images/gcloud-psql-gcp-14:2025-02-18-113033-c2322f5
  filesFrom:
  - secret: migration-user
    mountPath: /var/run/secrets/nais.io/migration-user
  - emptyDir: {}
    mountPath: /data
  - emptyDir: {}
    mountPath: /db/.config
  resources:
    requests:
      cpu: 500m
      memory: 512Mi #dette er maks
  replicas:
    max: 1
    min: 1
