apiVersion: v1
kind: Pod
metadata:
  name: gcloud
spec:
  containers:
  - image: navikt/gcloud-psql:14
    imagePullPolicy: Always
    name: gcloud
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: false
      runAsNonRoot: true
      runAsUser: 65532
      seccompProfile:
        type: RuntimeDefault
    volumeMounts:
    - mountPath: /etc/ssl/ca-bundle.pem
      name: ca-bundle-pem
      readOnly: true
      subPath: ca-bundle.pem
    - mountPath: /data
      name: tmpdir
    - mountPath: /var/run/secrets/nais.io/migration-user
      name: migration-user
      readOnly: true
  volumes:
  - configMap:
      defaultMode: 420
      name: ca-bundle-pem
    name: ca-bundle-pem
  - emptyDir: {}
    name: tmpdir
  - secret:
      defaultMode: 420
      secretName: migration-user
    name: migration-user
