name: Update gcloud.yaml
on:
  push:
    paths:
      - Dockerfile
      - '.github/workflows/update_pod_spec.yaml'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: navikt/github-app-token-generator@v1
        id: get-token
        with:
          private-key: ${{ secrets.PRIVATE_KEY }}
          app-id: ${{ secrets.APP_ID }}
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ steps.get-token.outputs.token }}

      - run: echo "IMAGE=ghcr.io/navikt/gcloud-psql:$(git log -1 --pretty=%ad --date=format:%Y-%m-%d)-$(git log --pretty=format:'%h' -n 1)" >> $GITHUB_ENV
      - run: docker build -t $IMAGE .
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker push $IMAGE

      - run: sed -i -e "s|ghcr.io.*|$IMAGE|" gcloud.yaml
      - name: Commit to repo
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit -am "ci: new release of gcloud-psql"
          git push
